#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${ADGUARD_DOMESTIC_UPSTREAMS_OUT:-${ROOT_DIR}/adguard/conf/upstream-domestic.conf}"
TMP="${OUT}.download"
SRC="${TMP}.source"
if [[ -n "${ADGUARD_DOMESTIC_DOMAIN_LIST_URLS:-}" ]]; then
  read -r -a LIST_URLS <<< "${ADGUARD_DOMESTIC_DOMAIN_LIST_URLS}"
elif [[ -n "${ADGUARD_DOMESTIC_DOMAIN_LIST_URL:-}" ]]; then
  LIST_URLS=("${ADGUARD_DOMESTIC_DOMAIN_LIST_URL}")
else
  LIST_URLS=(
    "https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"
    "https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list@master/accelerated-domains.china.conf"
  )
fi
CN_DNS_1="${ADGUARD_DOMESTIC_DNS_1:-119.29.29.29}"
CN_DNS_2="${ADGUARD_DOMESTIC_DNS_2:-223.5.5.5}"
DEFAULT_UPSTREAM="${ADGUARD_DEFAULT_UPSTREAM:-127.0.0.1:1053}"
BACKUP="${OUT}.bak"
RELOAD=0

case "${1:-}" in
  --reload)
    RELOAD=1
    ;;
  "")
    ;;
  *)
    echo "usage: $0 [--reload]" >&2
    exit 2
    ;;
esac

mkdir -p "$(dirname "${OUT}")"

downloaded=0
for url in "${LIST_URLS[@]}"; do
  if curl -fsSL --http1.1 --connect-timeout 15 --max-time 180 --retry 4 --retry-delay 3 --retry-all-errors "${url}" > "${SRC}"; then
    downloaded=1
    break
  fi
  echo "download failed: ${url}" >&2
done

if [[ "${downloaded}" != "1" ]]; then
  rm -f "${SRC}" "${TMP}"
  if [[ -s "${OUT}" ]]; then
    echo "adguard domestic upstreams download failed; keeping existing ${OUT}" >&2
    exit 0
  fi
  echo "adguard domestic upstreams download failed and no existing ${OUT}" >&2
  exit 1
fi

awk -F/ -v dns1="${CN_DNS_1}" -v dns2="${CN_DNS_2}" '
      BEGIN {
        print "# Generated by maintenance/adguard/update-domestic-upstreams.sh";
        print "# Domestic domains use real DNS answers so OpenWrt can bypass Pi/Mihomo by MIHOMO_CN4.";
      }
      /^server=\/[^/]+\/[^/]+/ {
        domain=$2;
        if (domain == "" || seen[domain]++) {
          next;
        }
        print "[/" domain "/]" dns1;
        if (dns2 != "") {
          print "[/" domain "/]" dns2;
        }
      }
    ' "${SRC}" > "${TMP}"
rm -f "${SRC}"

cat >> "${TMP}" <<EOF
# Default path: keep non-domestic domains on Mihomo DNS/fake-ip.
${DEFAULT_UPSTREAM}
EOF

if [[ -f "${OUT}" ]] && cmp -s "${TMP}" "${OUT}"; then
  rm -f "${TMP}"
  echo "adguard domestic upstreams unchanged"
  exit 0
fi

if [[ -f "${OUT}" ]]; then
  cp "${OUT}" "${BACKUP}"
fi

mv "${TMP}" "${OUT}"
echo "wrote ${OUT}"

if [[ "${RELOAD}" != "1" ]]; then
  exit 0
fi

if ! docker exec adguardhome /opt/adguardhome/AdGuardHome \
  -c /opt/adguardhome/conf/AdGuardHome.yaml \
  -w /opt/adguardhome/work \
  --check-config; then
  if [[ -f "${BACKUP}" ]]; then
    cp "${BACKUP}" "${OUT}"
  fi
  exit 1
fi

docker exec adguardhome /opt/adguardhome/AdGuardHome \
  -c /opt/adguardhome/conf/AdGuardHome.yaml \
  -w /opt/adguardhome/work \
  -s reload
echo "adguardhome reloaded"
