"""Shared review-renderer helpers for module-owned adapters."""

from __future__ import annotations

import json
from typing import Any


def as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def review_scalar(value: Any) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def append_review_list(lines: list[str], indent: str, key: str, values: list[str]) -> None:
    if values:
        lines.append(f"{indent}{key}:")
        for value in values:
            lines.append(f"{indent}  - {review_scalar(value)}")


def append_review_field(lines: list[str], indent: str, key: str, value: Any) -> None:
    if value:
        lines.append(f"{indent}{key}: {review_scalar(value)}")


def service_by_id(services: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {
        str(service.get("id") or ""): service
        for service in services
        if isinstance(service, dict) and service.get("id")
    }


def ports_for_service(ports: list[dict[str, Any]], service: dict[str, Any]) -> list[dict[str, Any]]:
    service_id = str(service.get("id") or "")
    service_name = str(service.get("name") or "")
    return [
        port
        for port in ports
        if isinstance(port, dict) and (port.get("service_id") == service_id or port.get("service") == service_name)
    ]


def remote_access_review_lines(
    *,
    artifact_id: str,
    target_path: str,
    title: str,
    note: str,
    entries: list[dict[str, Any]],
    services: list[dict[str, Any]],
    ports: list[dict[str, Any]],
    source_tool: str,
    required_secrets: list[str],
) -> list[str]:
    services_by_id = service_by_id(services)
    service_ids = sorted({str(entry.get("service_id") or "") for entry in entries if entry.get("service_id")})
    lines = [
        "# Generated by HomeNet config review renderer.",
        f"# Artifact: {artifact_id}",
        f"# Target path when applied by source tools: {target_path}",
        f"# {title}",
        f"# {note}",
        "# This is a deterministic review inventory, not a deployable service config.",
        "# It contains no tokens, keys, private WireGuard material, cookies, or session data.",
        "",
        "remote_entries:",
    ]
    if entries:
        for entry in entries:
            lines.append(f"  - id: {review_scalar(entry.get('id', ''))}")
            lines.append(f"    name: {review_scalar(entry.get('name', ''))}")
            lines.append(f"    kind: {review_scalar(entry.get('kind', ''))}")
            append_review_field(lines, "    ", "href", entry.get("href"))
            append_review_field(lines, "    ", "target", entry.get("target"))
            append_review_field(lines, "    ", "service_id", entry.get("service_id"))
            append_review_field(lines, "    ", "status_source", entry.get("status_source"))
    else:
        lines.append("  []")
    lines.append("")
    lines.append("target_services:")
    if service_ids:
        for service_id in service_ids:
            service = services_by_id.get(service_id, {"id": service_id})
            lines.append(f"  - id: {review_scalar(service_id)}")
            append_review_field(lines, "    ", "name", service.get("name") or service_id)
            append_review_field(lines, "    ", "role", service.get("role"))
            append_review_field(lines, "    ", "host", service.get("host"))
            append_review_field(lines, "    ", "local_url", service.get("local_url"))
            append_review_field(lines, "    ", "remote_url", service.get("remote_url"))
            exposed = ports_for_service(ports, service)
            if exposed:
                lines.append("    ports:")
                for port in exposed:
                    value = f"{port.get('host', '')}:{port.get('port', '')}/{port.get('proto', '')}"
                    lines.append(f"      - {review_scalar(value)}")
    else:
        lines.append("  []")
    lines.append("")
    lines.append("required_secrets:")
    if required_secrets:
        for secret in required_secrets:
            lines.append(f"  - {review_scalar(secret)}")
    else:
        lines.append("  []")
    lines.extend([
        "",
        "x-homenet-review:",
        f"  entry_count: {len(entries)}",
        f"  target_service_count: {len(service_ids)}",
        "  deployable: false",
        f"  source_tool: {review_scalar(source_tool)}",
        "  live_apply: disabled",
        "  note: Review-only inventory; source tools still own tokens, credentials, policies, certificates, and live route changes.",
    ])
    return lines


def service_config_review_lines(
    *,
    artifact_id: str,
    target_path: str,
    title: str,
    note: str,
    service_ids: list[str],
    services: list[dict[str, Any]],
    ports: list[dict[str, Any]],
    source_tool: str,
    required_secrets: list[str],
    dependencies: list[str],
) -> list[str]:
    services_by_id = service_by_id(services)
    lines = [
        "# Generated by HomeNet config review renderer.",
        f"# Artifact: {artifact_id}",
        f"# Target path when applied by source tools: {target_path}",
        f"# {title}",
        f"# {note}",
        "# This is a deterministic service review inventory, not a deployable service config.",
        "# It contains no tokens, passwords, private keys, cookies, sessions, or service database content.",
        "",
        "services:",
    ]
    selected = [services_by_id[service_id] for service_id in service_ids if service_id in services_by_id]
    if selected:
        for service in selected:
            service_id = str(service.get("id") or "")
            lines.append(f"  - id: {review_scalar(service_id)}")
            append_review_field(lines, "    ", "name", service.get("name") or service_id)
            append_review_field(lines, "    ", "owner", service.get("owner"))
            append_review_field(lines, "    ", "runtime", service.get("runtime"))
            append_review_field(lines, "    ", "host", service.get("host"))
            append_review_field(lines, "    ", "role", service.get("role"))
            append_review_field(lines, "    ", "local_url", service.get("local_url"))
            append_review_field(lines, "    ", "remote_url", service.get("remote_url"))
            exposed = ports_for_service(ports, service)
            if exposed:
                lines.append("    ports:")
                for port in exposed:
                    endpoint = f"{port.get('host', '')}:{port.get('port', '')}/{port.get('proto', '')}"
                    lines.append(f"      - {review_scalar(endpoint)}")
                    append_review_field(lines, "        ", "scope", port.get("scope"))
                    append_review_field(lines, "        ", "note", port.get("note"))
    else:
        lines.append("  []")
    lines.append("")
    lines.append("dependencies:")
    if dependencies:
        for dependency in dependencies:
            lines.append(f"  - {review_scalar(dependency)}")
    else:
        lines.append("  []")
    lines.append("")
    lines.append("required_secrets:")
    if required_secrets:
        for secret in required_secrets:
            lines.append(f"  - {review_scalar(secret)}")
    else:
        lines.append("  []")
    lines.extend([
        "",
        "x-homenet-review:",
        f"  service_count: {len(selected)}",
        "  deployable: false",
        f"  source_tool: {review_scalar(source_tool)}",
        "  live_apply: disabled",
        "  note: Review-only inventory; source tools still own full config files, volumes, credentials, migrations, and live restarts.",
    ])
    return lines
