"""DNS Layer review renderers.

These functions are module-owned adapters for review-only generated artifacts.
They do not read live infrastructure, resolve secrets, or write files.
"""

from __future__ import annotations

from typing import Any


def render_adguard_domestic_upstreams_review(
    *,
    networks: dict[str, Any],
    gateway: str,
) -> dict[str, Any]:
    """Render the AdGuard domestic upstream review artifact."""
    lines = [
        "# Generated by HomeNet config review renderer.",
        "# Artifact: dns-layer.domestic-upstreams",
        "# Target path when applied by source tools: adguard/conf/upstream-domestic.conf",
        "# This file contains deterministic local rules and the upstream-generation contract.",
        "# It is not AdGuardHome.yaml and contains no credentials.",
        "",
        "# Local home zones should resolve through the OpenWrt Gateway.",
    ]
    local_zone_count = 0
    if gateway:
        lines.append(f"[/lan/]{gateway}")
        lines.append(f"[/local/]{gateway}")
        local_zone_count = 2
    else:
        lines.append("# gateway is not declared; local zone rules cannot be rendered.")
    lines.extend([
        "",
        "# Domestic public domain rules are materialized by:",
        "#   maintenance/adguard/update-domestic-upstreams.sh",
        "# Default source list:",
        "#   https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf",
        "# Fallback source list:",
        "#   https://cdn.jsdelivr.net/gh/felixonmars/dnsmasq-china-list@master/accelerated-domains.china.conf",
        "# Domestic DNS upstream defaults:",
        "#   ADGUARD_DOMESTIC_DNS_1=119.29.29.29",
        "#   ADGUARD_DOMESTIC_DNS_2=223.5.5.5",
        "# Non-domestic default path:",
        "#   ADGUARD_DEFAULT_UPSTREAM=127.0.0.1:1053",
        "",
        "# Network DNS intent from instance metadata:",
    ])
    for network_id, network in networks.items():
        if not isinstance(network, dict) or network.get("enabled") is False:
            continue
        dns_mode = str(network.get("dns_mode") or "")
        if dns_mode in {"home", "public"}:
            lines.append(f"# network={network_id} cidr={network.get('cidr', '')} dns_mode={dns_mode}")
    lines.extend([
        "",
        "# Review command:",
        "#   ADGUARD_DOMESTIC_UPSTREAMS_OUT=/tmp/upstream-domestic.conf bash maintenance/adguard/update-domestic-upstreams.sh",
        "# Live source-tool command after backup/review:",
        "#   bash maintenance/adguard/update-domestic-upstreams.sh --reload",
    ])
    return {
        "lines": lines,
        "local_zone_rules": local_zone_count,
        "implementation_surface": "modules/renderers/dns_layer.py::render_adguard_domestic_upstreams_review",
    }
