"""Module-owned observability review renderers."""

from __future__ import annotations

from typing import Any

from modules.renderers.common import append_review_field, review_scalar


def render_kuma_import_plan_review(*, kuma: dict[str, Any]) -> dict[str, Any]:
    monitors = [monitor for monitor in kuma.get("monitors", []) if isinstance(monitor, dict)]
    auto = [monitor for monitor in monitors if monitor.get("auto_importable")]
    manual = [monitor for monitor in monitors if not monitor.get("auto_importable")]
    by_group: dict[str, int] = {}
    by_type: dict[str, int] = {}
    for monitor in monitors:
        group = str(monitor.get("group") or "Other")
        kind = str(monitor.get("type") or "unknown")
        by_group[group] = by_group.get(group, 0) + 1
        by_type[kind] = by_type.get(kind, 0) + 1

    lines = [
        "# Generated by HomeNet config review renderer.",
        "# Artifact: observability-homenet.kuma-import-plan",
        "# Target path when applied by source tools: homenet.kuma_import_plan.v1",
        "# Uptime Kuma import review inventory.",
        "# This is a metadata-only review artifact. It does not read or write the Kuma database.",
        "# It contains no session data, notification tokens, database rows, passwords, or API credentials.",
        "",
        "summary:",
        f"  monitor_candidates: {len(monitors)}",
        f"  auto_importable: {len(auto)}",
        f"  manual: {len(manual)}",
        "  deployable: false",
        "",
        "by_group:",
    ]
    if by_group:
        for group in sorted(by_group):
            lines.append(f"  {group}: {by_group[group]}")
    else:
        lines.append("  {}")
    lines.append("")
    lines.append("by_type:")
    if by_type:
        for kind in sorted(by_type):
            lines.append(f"  {kind}: {by_type[kind]}")
    else:
        lines.append("  {}")
    lines.extend([
        "",
        "candidate_actions:",
        f"  create_or_match_after_db_diff: {len(auto)}",
        f"  manual_or_unsupported: {len(manual)}",
        "  update_existing: requires read-only DB diff",
        "  delete_existing: never generated by HomeNet",
        "",
        "manual_candidates:",
    ])
    if manual:
        for monitor in manual:
            lines.append(f"  - name: {review_scalar(monitor.get('name', ''))}")
            append_review_field(lines, "    ", "type", monitor.get("type"))
            append_review_field(lines, "    ", "target", monitor.get("target"))
            append_review_field(lines, "    ", "reason", "unsupported by automatic import")
    else:
        lines.append("  []")
    lines.extend([
        "",
        "required_apply_gates:",
        "  - read Uptime Kuma SQLite through immutable read-only diff first",
        "  - create timestamped DB backup before any write",
        "  - require explicit APPLY-KUMA confirmation for writes",
        "  - never delete extra/operator-owned monitors automatically",
        "  - treat interval updates and target/type changes as optional review actions",
        "",
        "x-homenet-review:",
        "  deployable: false",
        "  source_tool: \"Uptime Kuma UI/DB + HomeNet guarded import workflow\"",
        "  live_apply: disabled",
        "  note: Review-only inventory; real import plan requires a read-only DB diff and a backup-confirmed apply workflow.",
    ])
    return {
        "lines": lines,
        "monitor_candidates": len(monitors),
        "auto_importable": len(auto),
        "implementation_surface": "modules/renderers/observability.py::render_kuma_import_plan_review",
    }
