"""Module-owned OpenWrt/UCI review renderers."""

from __future__ import annotations

from typing import Any

from modules.renderers.common import append_review_field, as_list, review_scalar


def uci_review_lines(
    *,
    artifact_id: str,
    target_path: str,
    title: str,
    note: str,
    sections: list[dict[str, Any]],
    source_tool: str,
) -> list[str]:
    lines = [
        "# Generated by HomeNet config review renderer.",
        f"# Artifact: {artifact_id}",
        f"# Target path when applied by source tools: {target_path}",
        f"# {title}",
        f"# {note}",
        "# This is a deterministic review inventory, not executable UCI.",
        "# It contains no Wi-Fi passwords, private keys, tokens, cookies, or session data.",
        "",
        "uci_intent:",
    ]
    if sections:
        for section in sections:
            lines.append(f"  - type: {review_scalar(section.get('type', ''))}")
            append_review_field(lines, "    ", "name", section.get("name"))
            append_review_field(lines, "    ", "purpose", section.get("purpose"))
            options = section.get("options", {})
            if isinstance(options, dict) and options:
                lines.append("    options:")
                for key in sorted(options):
                    value = options[key]
                    if isinstance(value, list):
                        lines.append(f"      {key}:")
                        for item in value:
                            lines.append(f"        - {review_scalar(item)}")
                    else:
                        lines.append(f"      {key}: {review_scalar(value)}")
    else:
        lines.append("  []")
    lines.extend([
        "",
        "x-homenet-review:",
        f"  section_count: {len(sections)}",
        "  deployable: false",
        f"  source_tool: {review_scalar(source_tool)}",
        "  live_apply: disabled",
        "  note: Review-only inventory; exact UCI commands still require source-tool rendering, backup, rollback, and live verification.",
    ])
    return lines


def gateway_network_sections(networks: dict[str, Any], runtime: dict[str, Any], wifi: dict[str, Any], server_host: str) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = []
    gateway = str(runtime.get("openwrt_gateway") or "")
    for network_id, network in sorted(networks.items()):
        if not isinstance(network, dict) or network.get("enabled") is False:
            continue
        options: dict[str, Any] = {
            "interface": network_id,
            "cidr": network.get("cidr", ""),
            "gateway": network.get("gateway", ""),
            "dns_mode": network.get("dns_mode", ""),
            "proxy_mode": network.get("proxy_mode", ""),
            "dhcp": network.get("dhcp", ""),
        }
        if gateway and network.get("gateway") == gateway:
            options["gateway_owner"] = "OpenWrt Gateway"
        if server_host and network.get("dns_mode") == "home":
            options["home_dns_runtime"] = server_host
        if network_id == "ops":
            options["maintenance_path"] = "direct WAN, bypass transparent proxy, limited server access"
        if network_id == "modem":
            options["management_path"] = "upstream modem management network; not a home client LAN"
        sections.append({
            "type": "interface",
            "name": network_id,
            "purpose": network.get("purpose", ""),
            "options": options,
        })

    room_ap = runtime.get("room_ap", {}) if isinstance(runtime.get("room_ap"), dict) else {}
    if room_ap:
        relay_wifi = wifi.get("relay_5g", {}) if isinstance(wifi.get("relay_5g"), dict) else {}
        main_wifi = wifi.get("main", {}) if isinstance(wifi.get("main"), dict) else {}
        sections.append({
            "type": "downstream-ap",
            "name": "room-ap",
            "purpose": room_ap.get("role", "Bedroom coverage AP / relay"),
            "options": {
                "host": room_ap.get("host", ""),
                "type": room_ap.get("type", "openwrt-relay"),
                "lan_mode": "bridge/relay; no independent DHCP authority",
                "client_ssid": main_wifi.get("ssid", ""),
                "backhaul_ssid": relay_wifi.get("ssid", ""),
            },
        })
    return sections


def gateway_dhcp_sections(networks: dict[str, Any], server_host: str) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = []
    for network_id, network in sorted(networks.items()):
        if not isinstance(network, dict) or network.get("enabled") is False:
            continue
        dhcp_range = str(network.get("dhcp") or "")
        if not dhcp_range:
            continue
        options: dict[str, Any] = {
            "interface": network_id,
            "cidr": network.get("cidr", ""),
            "gateway": network.get("gateway", ""),
            "dhcp_range": dhcp_range,
            "dns_mode": network.get("dns_mode", ""),
            "proxy_mode": network.get("proxy_mode", ""),
        }
        if server_host and network.get("dns_mode") == "home":
            options["dhcp_dns"] = server_host
        elif network.get("dns_mode") == "public":
            options["dhcp_dns"] = "public upstream via gateway"
        sections.append({
            "type": "dhcp-pool",
            "name": network_id,
            "purpose": network.get("purpose", ""),
            "options": options,
        })
    return sections


def gateway_firewall_sections(networks: dict[str, Any], server_host: str) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = []
    for network_id, network in sorted(networks.items()):
        if not isinstance(network, dict) or network.get("enabled") is False or network_id == "modem":
            continue
        options: dict[str, Any] = {
            "network": network_id,
            "input": "ACCEPT" if network_id in {"lan", "ops"} else "REJECT",
            "output": "ACCEPT",
            "forward": "ACCEPT" if network_id == "lan" else "REJECT",
            "wan_forward": "ACCEPT",
            "dns_mode": network.get("dns_mode", ""),
            "proxy_mode": network.get("proxy_mode", ""),
        }
        if network_id == "ops" and server_host:
            options["allowed_to_server"] = [f"{server_host}:22/tcp", f"{server_host}:9999/tcp"]
            options["transparent_proxy"] = "bypass"
        if network_id in {"iot", "guest"}:
            options["lan_isolation"] = "deny client-to-LAN by default"
        sections.append({
            "type": "firewall-zone",
            "name": network_id,
            "purpose": network.get("purpose", ""),
            "options": options,
        })
    return sections


def wireless_sections_for_broadcaster(wifi: dict[str, Any], broadcaster_keyword: str) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = []
    keyword = broadcaster_keyword.lower()
    for wifi_id, item in sorted(wifi.items()):
        if not isinstance(item, dict):
            continue
        broadcasters = [str(value).lower() for value in as_list(item.get("broadcast_by"))]
        if not any(keyword in value for value in broadcasters):
            continue
        sections.append({
            "type": "wifi-iface",
            "name": wifi_id,
            "purpose": item.get("purpose", ""),
            "options": {
                "ssid": item.get("ssid", ""),
                "network": item.get("network", ""),
                "band": item.get("band", ""),
                "broadcast_by": as_list(item.get("broadcast_by")),
            },
        })
    return sections


def dns_forwarding_sections(networks: dict[str, Any], server_host: str, gateway: str) -> list[dict[str, Any]]:
    sections: list[dict[str, Any]] = []
    for network_id, network in sorted(networks.items()):
        if not isinstance(network, dict) or network.get("enabled") is False:
            continue
        dns_mode = str(network.get("dns_mode") or "")
        if dns_mode not in {"home", "public"}:
            continue
        options: dict[str, Any] = {
            "network": network_id,
            "dns_mode": dns_mode,
            "gateway": network.get("gateway", ""),
        }
        if dns_mode == "home" and server_host:
            options["forward_to"] = f"AdGuard on {server_host}"
        elif dns_mode == "public":
            options["forward_to"] = "public DNS through OpenWrt"
        if gateway:
            options["local_zone_owner"] = gateway
        sections.append({
            "type": "dns-forwarding",
            "name": network_id,
            "purpose": network.get("purpose", ""),
            "options": options,
        })
    return sections


def ops_network_sections(networks: dict[str, Any]) -> list[dict[str, Any]]:
    ops = networks.get("ops", {}) if isinstance(networks.get("ops"), dict) else {}
    if not ops:
        return []
    return [{
        "type": "interface",
        "name": "ops",
        "purpose": ops.get("purpose", ""),
        "options": {
            "cidr": ops.get("cidr", ""),
            "gateway": ops.get("gateway", ""),
            "dhcp": ops.get("dhcp", ""),
            "dns_mode": ops.get("dns_mode", ""),
            "proxy_mode": ops.get("proxy_mode", ""),
        },
    }]


def ops_wireless_sections(wifi: dict[str, Any]) -> list[dict[str, Any]]:
    ops = wifi.get("ops", {}) if isinstance(wifi.get("ops"), dict) else {}
    if not ops:
        return []
    return [{
        "type": "wifi-iface",
        "name": "ops",
        "purpose": ops.get("purpose", ""),
        "options": {
            "ssid": ops.get("ssid", ""),
            "network": ops.get("network", ""),
            "band": ops.get("band", ""),
            "broadcast_by": as_list(ops.get("broadcast_by")),
        },
    }]


def ops_firewall_sections(networks: dict[str, Any], server_host: str) -> list[dict[str, Any]]:
    ops = networks.get("ops", {}) if isinstance(networks.get("ops"), dict) else {}
    if not ops:
        return []
    allowed = []
    if server_host:
        allowed = [f"{server_host}:22/tcp", f"{server_host}:9999/tcp"]
    return [{
        "type": "firewall-zone",
        "name": "ops",
        "purpose": "Independent maintenance path with direct WAN and limited server access.",
        "options": {
            "network": "ops",
            "cidr": ops.get("cidr", ""),
            "wan_forward": "ACCEPT",
            "lan_forward": "REJECT by default",
            "transparent_proxy": "bypass",
            "allowed_to_server": allowed,
        },
    }]


def room_network_sections(runtime: dict[str, Any], wifi: dict[str, Any]) -> list[dict[str, Any]]:
    room_ap = runtime.get("room_ap", {}) if isinstance(runtime.get("room_ap"), dict) else {}
    host = str(room_ap.get("host") or "")
    if not host:
        return []
    return [{
        "type": "room-ap-network",
        "name": "room-ap",
        "purpose": room_ap.get("role", "Bedroom coverage AP / relay"),
        "options": {
            "host": host,
            "type": room_ap.get("type", "openwrt-relay"),
            "lan_bridge": "same LAN; no independent DHCP authority",
            "main_ssid": (wifi.get("main", {}) if isinstance(wifi.get("main"), dict) else {}).get("ssid", ""),
            "backhaul_ssid": (wifi.get("relay_5g", {}) if isinstance(wifi.get("relay_5g"), dict) else {}).get("ssid", ""),
        },
    }]


def room_firewall_sections(runtime: dict[str, Any]) -> list[dict[str, Any]]:
    room_ap = runtime.get("room_ap", {}) if isinstance(runtime.get("room_ap"), dict) else {}
    host = str(room_ap.get("host") or "")
    if not host:
        return []
    return [{
        "type": "room-ap-firewall",
        "name": "room-ap",
        "purpose": "Coverage AP should not become a second routed gateway.",
        "options": {
            "host": host,
            "dhcp_authority": "disabled",
            "nat": "disabled",
            "management_from_lan": "allow LuCI/SSH from trusted LAN",
            "client_isolation": "follow upstream LAN policy",
        },
    }]


def render_gateway_network_inventory(*, networks: dict[str, Any], runtime: dict[str, Any], wifi: dict[str, Any], server_host: str) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="gateway-openwrt.network",
        target_path="/etc/config/network",
        title="OpenWrt Gateway network interface inventory.",
        note="Gateway network owns declared LAN/IoT/Guest/Maintenance/modem interfaces and downstream AP boundaries.",
        sections=gateway_network_sections(networks, runtime, wifi, server_host),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_gateway_network_inventory"}


def render_gateway_dhcp_inventory(*, networks: dict[str, Any], server_host: str) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="gateway-openwrt.dhcp",
        target_path="/etc/config/dhcp",
        title="OpenWrt DHCP pool and DNS handoff inventory.",
        note="OpenWrt owns address assignment; server-host DNS is only referenced as an intended upstream.",
        sections=gateway_dhcp_sections(networks, server_host),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_gateway_dhcp_inventory"}


def render_gateway_firewall_inventory(*, networks: dict[str, Any], server_host: str) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="gateway-openwrt.firewall",
        target_path="/etc/config/firewall",
        title="OpenWrt firewall zone inventory.",
        note="Gateway firewall owns LAN/IoT/Guest/Maintenance boundaries and WAN forwarding policy.",
        sections=gateway_firewall_sections(networks, server_host),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_gateway_firewall_inventory"}


def render_gateway_wireless_inventory(*, wifi: dict[str, Any]) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="gateway-openwrt.wireless",
        target_path="/etc/config/wireless",
        title="OpenWrt Gateway wireless inventory.",
        note="Gateway wireless owns SSID broadcast intent without Wi-Fi passwords.",
        sections=wireless_sections_for_broadcaster(wifi, "OpenWrt Gateway"),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_gateway_wireless_inventory"}


def render_dns_router_forwarding_inventory(*, networks: dict[str, Any], server_host: str, gateway: str) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="dns-layer.router-forwarding",
        target_path="/etc/config/dhcp",
        title="OpenWrt DNS forwarding inventory.",
        note="Router-side dnsmasq forwards eligible networks to the declared home DNS path.",
        sections=dns_forwarding_sections(networks, server_host, gateway),
        source_tool="OpenWrt dnsmasq / AdGuard",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_dns_router_forwarding_inventory"}


def render_ops_network_inventory(*, networks: dict[str, Any]) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="maintenance-wifi.maintenance-network",
        target_path="/etc/config/network",
        title="Maintenance Wi-Fi network inventory.",
        note="Maintenance network is the low-dependency maintenance path and should bypass home DNS/proxy.",
        sections=ops_network_sections(networks),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_ops_network_inventory"}


def render_ops_wireless_inventory(*, wifi: dict[str, Any]) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="maintenance-wifi.maintenance-wireless",
        target_path="/etc/config/wireless",
        title="Maintenance Wi-Fi wireless inventory.",
        note="Maintenance SSID is intended for maintenance access and contains no password in generated output.",
        sections=ops_wireless_sections(wifi),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_ops_wireless_inventory"}


def render_ops_firewall_inventory(*, networks: dict[str, Any], server_host: str) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="maintenance-wifi.maintenance-firewall",
        target_path="/etc/config/firewall",
        title="Maintenance Wi-Fi firewall inventory.",
        note="Maintenance firewall keeps direct WAN while limiting access back into the main LAN.",
        sections=ops_firewall_sections(networks, server_host),
        source_tool="OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_ops_firewall_inventory"}


def render_room_network_inventory(*, runtime: dict[str, Any], wifi: dict[str, Any]) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="room-ap.room-network",
        target_path="/etc/config/network",
        title="Room AP network inventory.",
        note="Room AP is modeled as coverage/relay, not as an independent DHCP gateway.",
        sections=room_network_sections(runtime, wifi),
        source_tool="Room AP OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_room_network_inventory"}


def render_room_wireless_inventory(*, wifi: dict[str, Any]) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="room-ap.room-wireless",
        target_path="/etc/config/wireless",
        title="Room AP wireless inventory.",
        note="Room AP broadcasts only declared room-capable SSIDs and does not expose Wi-Fi passwords.",
        sections=wireless_sections_for_broadcaster(wifi, "WRT Room"),
        source_tool="Room AP OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_room_wireless_inventory"}


def render_room_firewall_inventory(*, runtime: dict[str, Any]) -> dict[str, Any]:
    lines = uci_review_lines(
        artifact_id="room-ap.room-firewall",
        target_path="/etc/config/firewall",
        title="Room AP firewall inventory.",
        note="Room AP should remain a bridge/relay endpoint and avoid becoming a second routed NAT device.",
        sections=room_firewall_sections(runtime),
        source_tool="Room AP OpenWrt UCI / LuCI",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/openwrt.py::render_room_firewall_inventory"}
