"""Module-owned Mihomo proxy review renderers."""

from __future__ import annotations

from typing import Any

from modules.renderers.common import append_review_field, ports_for_service, review_scalar, service_by_id
from modules.renderers.server_runtime import build_systemd_units_review_lines


def route_policy_review_lines(
    *,
    artifact_id: str,
    target_path: str,
    title: str,
    note: str,
    policies: list[dict[str, Any]],
    source_tool: str,
) -> list[str]:
    lines = [
        "# Generated by HomeNet config review renderer.",
        f"# Artifact: {artifact_id}",
        f"# Target path when applied by source tools: {target_path}",
        f"# {title}",
        f"# {note}",
        "# This is a deterministic route-policy review inventory, not executable firewall or ip rule syntax.",
        "# It contains no proxy subscription URL, controller secret, private key, token, cookie, or session data.",
        "",
        "route_policy_intent:",
    ]
    if policies:
        for policy in policies:
            lines.append(f"  - id: {review_scalar(policy.get('id', ''))}")
            append_review_field(lines, "    ", "purpose", policy.get("purpose"))
            options = policy.get("options", {})
            if isinstance(options, dict) and options:
                lines.append("    options:")
                for key in sorted(options):
                    value = options[key]
                    if isinstance(value, list):
                        lines.append(f"      {key}:")
                        for item in value:
                            lines.append(f"        - {review_scalar(item)}")
                    else:
                        lines.append(f"      {key}: {review_scalar(value)}")
    else:
        lines.append("  []")
    lines.extend([
        "",
        "x-homenet-review:",
        f"  policy_count: {len(policies)}",
        "  deployable: false",
        f"  source_tool: {review_scalar(source_tool)}",
        "  live_apply: disabled",
        "  note: Review-only inventory; exact firewall, nft/iptables, ip rule, and rollback commands require source-tool rendering and live verification.",
    ])
    return lines


def tproxy_policy_sections(networks: dict[str, Any], services: list[dict[str, Any]], ports: list[dict[str, Any]]) -> list[dict[str, Any]]:
    services_by_id = service_by_id(services)
    mihomo = services_by_id.get("mihomo", {"id": "mihomo"})
    mihomo_ports = ports_for_service(ports, mihomo)
    tproxy_targets = [
        f"{port.get('host', '')}:{port.get('port', '')}/{port.get('proto', '')}"
        for port in mihomo_ports
        if str(port.get("port") or "") in {"7892", "1053", "9090"}
    ]
    sections: list[dict[str, Any]] = []
    for network_id, network in sorted(networks.items()):
        if not isinstance(network, dict) or network.get("enabled") is False:
            continue
        proxy_mode = str(network.get("proxy_mode") or "")
        if proxy_mode not in {"transparent", "bypass", "direct"}:
            continue
        sections.append({
            "id": f"{network_id}-proxy-policy",
            "purpose": network.get("purpose", ""),
            "options": {
                "network": network_id,
                "cidr": network.get("cidr", ""),
                "proxy_mode": proxy_mode,
                "dns_mode": network.get("dns_mode", ""),
                "tproxy_targets": tproxy_targets,
                "policy": "mark and route selected traffic to Mihomo" if proxy_mode == "transparent" else "bypass transparent proxy",
                "route_table": "100 for transparent networks",
            },
        })
    return sections


def mihomo_config_review_lines(
    *,
    services: list[dict[str, Any]],
    ports: list[dict[str, Any]],
    networks: dict[str, Any],
    systemd_units: list[dict[str, Any]],
) -> list[str]:
    services_by_id = service_by_id(services)
    mihomo = services_by_id.get("mihomo", {"id": "mihomo", "name": "Mihomo Proxy"})
    mihomo_ports = ports_for_service(ports, mihomo)
    update_units = [
        unit
        for unit in systemd_units
        if str(unit.get("name") or "").startswith("mihomo-config-update")
    ]
    transparent_networks = [
        network_id
        for network_id, network in sorted(networks.items())
        if isinstance(network, dict)
        and network.get("enabled") is not False
        and str(network.get("proxy_mode") or "") == "transparent"
    ]
    bypass_networks = [
        network_id
        for network_id, network in sorted(networks.items())
        if isinstance(network, dict)
        and network.get("enabled") is not False
        and str(network.get("proxy_mode") or "") in {"bypass", "direct", "none"}
    ]

    lines = [
        "# Generated by HomeNet config review renderer.",
        "# Artifact: proxy-mihomo.mihomo-config",
        "# Target path when applied by source tools: mihomo/config.yaml",
        "# Mihomo service config inventory.",
        "# This is a deterministic review inventory, not a deployable Mihomo config file.",
        "# It contains secret names and policy intent only; it does not include provider URLs, nodes, controller secrets, cookies, or runtime cache.",
        "",
        "service:",
    ]
    append_review_field(lines, "  ", "id", mihomo.get("id") or "mihomo")
    append_review_field(lines, "  ", "name", mihomo.get("name") or "Mihomo Proxy")
    append_review_field(lines, "  ", "host", mihomo.get("host"))
    append_review_field(lines, "  ", "local_url", mihomo.get("local_url"))
    append_review_field(lines, "  ", "remote_url", mihomo.get("remote_url"))
    lines.append("")
    lines.append("ports:")
    if mihomo_ports:
        for port in mihomo_ports:
            endpoint = f"{port.get('host', '')}:{port.get('port', '')}/{port.get('proto', '')}"
            lines.append(f"  - endpoint: {review_scalar(endpoint)}")
            append_review_field(lines, "    ", "scope", port.get("scope"))
            append_review_field(lines, "    ", "note", port.get("note"))
    else:
        lines.append("  []")
    lines.extend([
        "",
        "provider_contract:",
        "  source: MIHOMO_CONFIG_URL",
        "  storage: /home/pi/.config/secrets/mihomo-update.env",
        "  legacy_fallback: maintenance/mihomo/mihomo-update.env placeholder only",
        "  local_target: mihomo/config.yaml",
        "  etag_state: maintenance/state/mihomo-config-update/config.etag",
        "  geosite_target: mihomo/GeoSite.dat",
        "  geosite_default_source: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat",
        "  validation: docker-compose exec mihomo /mihomo -t -f /root/.config/mihomo/config.yaml",
        "  reload: controller /configs plus fake-ip and dns cache flush",
        "",
        "policy_intent:",
        "  provider_group: subscription-provided groups and nodes remain provider-owned",
        "  explicit_proxy: mixed proxy on declared LAN port",
        "  tproxy: OpenWrt marks transparent networks to the Mihomo TProxy port",
        "  fake_ip_dns: AdGuard/default upstream may use Mihomo fake-ip DNS for non-domestic flow",
        "  domestic_dns: AdGuard domestic upstream rules keep China domains on real DNS answers",
        "  transparent_networks:",
    ])
    if transparent_networks:
        for network_id in transparent_networks:
            lines.append(f"    - {review_scalar(network_id)}")
    else:
        lines.append("    []")
    lines.append("  bypass_or_direct_networks:")
    if bypass_networks:
        for network_id in bypass_networks:
            lines.append(f"    - {review_scalar(network_id)}")
    else:
        lines.append("    []")
    lines.extend(["", "update_units:"])
    if update_units:
        for unit in update_units:
            lines.append(f"  - name: {review_scalar(unit.get('name', ''))}")
            append_review_field(lines, "    ", "path", unit.get("path"))
            append_review_field(lines, "    ", "kind", unit.get("kind"))
            append_review_field(lines, "    ", "purpose", unit.get("purpose"))
    else:
        lines.append("  []")
    lines.extend([
        "",
        "required_secrets:",
        "  - MIHOMO_CONFIG_URL",
        "  - MIHOMO_SECRET",
        "",
        "source_tools:",
        "  - maintenance/mihomo/update-mihomo-config.sh",
        "  - maintenance/systemd/mihomo-config-update.service",
        "  - maintenance/systemd/mihomo-config-update.timer",
        "  - Mihomo controller API",
        "",
        "x-homenet-review:",
        "  deployable: false",
        "  source_tool: Mihomo provider + local update script + Docker Compose",
        "  live_apply: disabled",
        "  note: Review-only inventory; provider URL, node list, controller secret, exact rules, and runtime cache remain in source tools and secret storage.",
    ])
    return lines


def render_mihomo_config_inventory(
    *,
    services: list[dict[str, Any]],
    ports: list[dict[str, Any]],
    networks: dict[str, Any],
    systemd_units: list[dict[str, Any]],
) -> dict[str, Any]:
    lines = mihomo_config_review_lines(
        services=services,
        ports=ports,
        networks=networks,
        systemd_units=systemd_units,
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/proxy_mihomo.py::render_mihomo_config_inventory"}


def render_mihomo_tproxy_policy_inventory(
    *,
    networks: dict[str, Any],
    services: list[dict[str, Any]],
    ports: list[dict[str, Any]],
) -> dict[str, Any]:
    lines = route_policy_review_lines(
        artifact_id="proxy-mihomo.tproxy-policy",
        target_path="/etc/config/firewall + policy route table 100",
        title="Mihomo TProxy route policy inventory.",
        note="OpenWrt owns transparent proxy marking/routing; generated output avoids executable firewall or route commands.",
        policies=tproxy_policy_sections(networks, services, ports),
        source_tool="OpenWrt firewall/nftables/iptables + ip rule",
    )
    return {"lines": lines, "implementation_surface": "modules/renderers/proxy_mihomo.py::render_mihomo_tproxy_policy_inventory"}


def render_mihomo_update_unit_inventory(*, units: list[dict[str, Any]]) -> dict[str, Any]:
    update_units = [
        unit
        for unit in units
        if str(unit.get("name") or "").startswith("mihomo-config-update")
    ]
    lines = build_systemd_units_review_lines(
        update_units,
        artifact_id="proxy-mihomo.update-unit",
        target_path="maintenance/systemd/mihomo-config-update.service + maintenance/systemd/mihomo-config-update.timer",
    )
    return {
        "lines": lines,
        "unit_count": len(update_units),
        "implementation_surface": "modules/renderers/proxy_mihomo.py::render_mihomo_update_unit_inventory",
    }
