"""Module-owned server-runtime review renderers."""

from __future__ import annotations

from typing import Any

from modules.renderers.common import append_review_field, append_review_list, as_list, review_scalar


def render_docker_compose_inventory(
    *,
    services: list[dict[str, Any]],
    ports: list[dict[str, Any]],
) -> dict[str, Any]:
    server_services = [service for service in services if service.get("runtime") == "server"]
    lines = [
        "# Generated by HomeNet config review renderer.",
        "# Artifact: server-runtime.docker-compose",
        "# Target path when applied by source tools: docker-compose.yml",
        "# This is a deterministic service inventory, not a deployable compose file.",
        "# It maps declared server-runtime services to owners, roles, and ports without env values.",
        "# Source of truth for live containers remains Docker Compose and service-native configuration.",
        "",
        "services:",
    ]
    for service in server_services:
        service_id = str(service.get("id") or "")
        owner = str(service.get("owner") or service_id)
        lines.append(f"  {service_id}:")
        lines.append(f"    x-homenet-owner: {owner}")
        lines.append(f"    x-homenet-role: {service.get('role', '')}")
        exposed = [
            port
            for port in ports
            if port.get("service_id") == service_id or port.get("service") == service.get("name")
        ]
        if exposed:
            lines.append("    x-homenet-ports:")
            for port in exposed:
                lines.append(f"      - {port.get('host', '')}:{port.get('port', '')}/{port.get('proto', '')}")
    lines.extend([
        "",
        "x-homenet-review:",
        f"  service_count: {len(server_services)}",
        "  deployable: false",
        "  source_tool: Docker Compose / systemd",
        "  live_apply: disabled",
        "  note: Review-only inventory; do not replace docker-compose.yml with this file.",
    ])
    return {
        "lines": lines,
        "server_services": len(server_services),
        "implementation_surface": "modules/renderers/server_runtime.py::render_docker_compose_inventory",
    }


def build_systemd_units_review_lines(
    units: list[dict[str, Any]],
    *,
    artifact_id: str = "server-runtime.systemd-units",
    target_path: str = "/etc/systemd/system/*.service and *.timer",
) -> list[str]:
    service_count = sum(1 for unit in units if str(unit.get("name", "")).endswith(".service"))
    timer_count = sum(1 for unit in units if str(unit.get("name", "")).endswith(".timer"))
    lines = [
        "# Generated by HomeNet config review renderer.",
        f"# Artifact: {artifact_id}",
        f"# Target path when applied by source tools: {target_path}",
        "# This is a deterministic inventory of repo-owned systemd units.",
        "# It does not install, enable, start, stop, restart, or reload systemd.",
        "",
        "units:",
    ]
    for unit in units:
        lines.append(f"  - name: {review_scalar(unit.get('name', ''))}")
        lines.append(f"    path: {review_scalar(unit.get('path', ''))}")
        lines.append(f"    kind: {review_scalar(unit.get('kind', ''))}")
        lines.append(f"    module_id: {review_scalar(unit.get('module_id', ''))}")
        append_review_field(lines, "    ", "purpose", unit.get("purpose"))
        append_review_field(lines, "    ", "description", unit.get("description"))
        append_review_list(lines, "    ", "wants", as_list(unit.get("wants")))
        append_review_list(lines, "    ", "after", as_list(unit.get("after")))
        append_review_field(lines, "    ", "service_type", unit.get("service_type"))
        append_review_field(lines, "    ", "user", unit.get("user"))
        append_review_field(lines, "    ", "group", unit.get("group"))
        append_review_field(lines, "    ", "working_directory", unit.get("working_directory"))
        append_review_list(lines, "    ", "exec_start", as_list(unit.get("exec_start")))
        append_review_list(lines, "    ", "exec_stop", as_list(unit.get("exec_stop")))
        append_review_field(lines, "    ", "restart", unit.get("restart"))
        append_review_field(lines, "    ", "restart_sec", unit.get("restart_sec"))
        append_review_field(lines, "    ", "remain_after_exit", unit.get("remain_after_exit"))
        append_review_list(lines, "    ", "timer_on_calendar", as_list(unit.get("timer_on_calendar")))
        append_review_list(lines, "    ", "timer_on_boot_sec", as_list(unit.get("timer_on_boot_sec")))
        append_review_list(lines, "    ", "timer_on_unit_active_sec", as_list(unit.get("timer_on_unit_active_sec")))
        append_review_field(lines, "    ", "timer_accuracy_sec", unit.get("timer_accuracy_sec"))
        append_review_field(lines, "    ", "timer_persistent", unit.get("timer_persistent"))
        append_review_field(lines, "    ", "timer_unit", unit.get("timer_unit"))
        append_review_list(lines, "    ", "install_wanted_by", as_list(unit.get("install_wanted_by")))
    lines.extend([
        "",
        "x-homenet-review:",
        f"  unit_count: {len(units)}",
        f"  service_count: {service_count}",
        f"  timer_count: {timer_count}",
        "  deployable: false",
        "  source_tool: systemd",
        "  live_apply: disabled",
        "  note: Review-only inventory; do not copy this file into /etc/systemd/system.",
    ])
    return lines


def render_systemd_units_inventory(*, units: list[dict[str, Any]]) -> dict[str, Any]:
    lines = build_systemd_units_review_lines(units)
    return {
        "lines": lines,
        "unit_count": len(units),
        "implementation_surface": "modules/renderers/server_runtime.py::render_systemd_units_inventory",
    }
